Axf/urls.py
#! encoding: utf-8
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/urls.py
#!_*_coding: utf-8 _*_
# @author =  lijun
# date  =  2018/7/3/003 10:37
from django.conf.urls import url

from app import views
from app.views import UserRegisterView, UserLoginView

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^market/(?P<typeid>\d+)/(?P<cid>\d+)/(?P<sort>\d+)/', views.market, name='market'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^sub_cart_good_num/', views.sub_cart_good_num, name='sub_cart_good_num'),
    url(r'^user/', UserRegisterView.as_view(), name='user'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^checkuser/', views.check_user, name='checkuser'),
    url(r'^user_login/', UserLoginView.as_view(), name='user_login'),

    #邮箱验证
    url(r'active/', views.active, name='active'),
    #改变选中状态
    url(r'changecarts/', views.changecarts, name='changecarts'),
    #改变全选状态
    url(r'changecartliststatus/', views.change_cart_liststatus, name='changecartliststatus'),

    url(r'add_cart_good_num/', views.add_cart_good_num, name='add_cart_good_num'),



]





templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    {% block extCSS %}

    {% endblock %}
</head>
<body>
    {% block header %}

    {% endblock %}

    {% block content %}

    {% endblock %}

    {% block footer %}

    {% endblock %}

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
    {% block extJS %}

    {% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/base.css' %}">
{% endblock %}

{% block header %}
<header></header>
{% endblock %}

{% block footer %}
<footer>
    <a href="{% url 'axf:home' %}" class="home">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>首页</dd>
        </dl>
    </a>
    <a href="{% url 'axf:market' typeid=104749 cid=0 sort=0 %}" class="market">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>闪购</dd>
        </dl>
    </a>
    <a href="{% url 'axf:cart' %}" class="cart">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>购物车</dd>
        </dl>
    </a>
    <a href="{% url 'axf:mine' %}" class="mine">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>我的</dd>
        </dl>
    </a>
</footer>
{% endblock %}






templates/base_user.html
{% extends 'base.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/user.css' %}">
{% endblock %}

{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/md5.js' %}"></script>
{% endblock %}

{% block header %}
    <header></header>
{% endblock %}








