Axf/urls.py
#! encoding: utf-8
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/urls.py
#!_*_coding: utf-8 _*_
# @author =  lijun
# date  =  2018/7/3/003 10:37
from django.conf.urls import url

from app import views
from app.views import UserRegisterView, UserLoginView

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^market/(?P<typeid>\d+)/(?P<cid>\d+)/(?P<sort>\d+)/', views.market, name='market'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^sub_cart_good_num/', views.sub_cart_good_num, name='sub_cart_good_num'),
    url(r'^user/', UserRegisterView.as_view(), name='user'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^checkuser/', views.check_user, name='checkuser'),
    url(r'^user_login/', UserLoginView.as_view(), name='user_login'),

    #邮箱验证
    url(r'active/', views.active, name='active'),
    #改变选中状态
    url(r'changecarts/', views.changecarts, name='changecarts'),
    #改变全选状态
    url(r'changecartliststatus/', views.change_cart_liststatus, name='changecartliststatus'),

    url(r'add_cart_good_num/', views.add_cart_good_num, name='add_cart_good_num'),



]





templates/user/user_active.html
<h4>Dear: {{ username }}</h4>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;感谢你成为泰山会VIP会员，但你还需要最后的认证，请点击下面链接激活用户</p>
<a href="{{ active_url }}">激活地址</a>

<p>如上述链接不可点击，请复制下面链接到浏览器中打开</p>
    <p>{{ active_url }}</p>

<p>&nbsp;&nbsp;&nbsp;&nbsp;BestWishes</p>
<p>德玛西亚皇子</p>




templates/user/user_login.html
{% extends 'base_user.html' %}
{% load static %}

{% block extCSS %}
        {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/user_register.css' %}">
{% endblock %}

{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/user_login.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="user_login" class="container">
         <form action="{% url 'axf:user_login' %}" method="post" enctype="multipart/form-data" onsubmit="return password_hash()">
    {% csrf_token %}
 <div class="form-group">
<label for="exampleInputUsername">用户名</label>
<input type="text" class="form-control" id="exampleInputUsername" name="u_username" placeholder="请输入用户名">
    
 </div>
  <div class="form-group">
    <label for="exampleInputPassword1">密码</label>
    <input type="password" class="form-control" id="exampleInputPassword" name="u_password" placeholder="请输入密码">
      <span id="username_info" style="color: red">{{ request.session.login_msg }}</span>
  </div>


  <button type="submit" class="btn btn-success btn-default">登录</button>
</form>
    </div>
{% endblock %}



templates/user/user_register.html
{% extends 'base_user.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/user_register.css' %}">
{% endblock %}


{% block extJS %}
        {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/user_register.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="user_register" class="container">
    <form action="{% url 'axf:user' %}" method="post" enctype="multipart/form-data" onsubmit="return check_input()">
    {% csrf_token %}
 <div class="form-group">
<label for="exampleInputUsername">用户名</label>
<input type="text" class="form-control" id="exampleInputUsername" name="u_username" placeholder="请输入用户名">
    <span id="username_info"></span>
 </div>
  <div class="form-group">
    <label for="exampleInputEmail1">邮箱</label>
      <input type="email" class="form-control" id="exampleInputEmail" name="u_email" placeholder="请输入邮箱">
    <span id="email_info"></span>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">密码</label>
    <input type="password" class="form-control" id="exampleInputPassword" name="u_password" placeholder="请输入密码">
    <span id="password_info"></span>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">确认密码</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="u_password1" placeholder="请确认密码">
    <span id="repassword_info"></span>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">头像</label>
    <input type="file" id="exampleInputFile" name="u_icon">
  </div>

  <button type="submit" class="btn btn-success btn-default">注册</button>
</form>
    </div>
    
{% endblock %}
