Axf/urls.py
#! encoding: utf-8
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/urls.py
#!_*_coding: utf-8 _*_
# @author =  lijun
# date  =  2018/7/3/003 10:37
from django.conf.urls import url

from app import views
from app.views import UserRegisterView, UserLoginView

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),
    url(r'^market/(?P<typeid>\d+)/(?P<cid>\d+)/(?P<sort>\d+)/', views.market, name='market'),
    url(r'^add_cart/', views.add_cart, name='add_cart'),
    url(r'^sub_cart_good_num/', views.sub_cart_good_num, name='sub_cart_good_num'),
    url(r'^user/', UserRegisterView.as_view(), name='user'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^checkuser/', views.check_user, name='checkuser'),
    url(r'^user_login/', UserLoginView.as_view(), name='user_login'),

    #邮箱验证
    url(r'active/', views.active, name='active'),
    #改变选中状态
    url(r'changecarts/', views.changecarts, name='changecarts'),
    #改变全选状态
    url(r'changecartliststatus/', views.change_cart_liststatus, name='changecartliststatus'),

    url(r'add_cart_good_num/', views.add_cart_good_num, name='add_cart_good_num'),



]





templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}

{% block extCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/mine/css/mine.css' %}">
{% endblock %}

{% block extJS %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/mine/js/mine.js' %}"></script>
{% endblock %}
{% block content %}
    <div id="mine">
        <div class="fixed">
            {% if is_login %}
                <span>
                    <img src="/static/upload/{{ user.u_icon.url }}" alt="{{ user.u_name }}">
                </span>
                <p>
                <span >{{ user.u_name }}</span>
            </p>

            <p class="level">
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>
                {% else %}
                 <span>
                <span class="glyphicon glyphicon-user"></span>
            </span>

            <p>
                <span class="not-login">未登录</span>
            </p>

            <p class="level">
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>

             <div id="regis">
                    <a href="{% url 'axf:user' %}">注册</a>
                </div>           
            {% endif %}
            

            <p class="collect">
               <span class="glyphicon glyphicon-heart"></span>
               <span>收藏</span>
            </p>
        </div>

        <div class="mine_info">
            <p>
                <span>我的订单</span>
                <a href="#">查看全部订单&gt;</a>
            </p>

            <nav id="nav">
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>待付款</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            <dd>待收货</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-pencil"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-retweet"></span>
                            </dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>
            </nav>

            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-bullhorn"></span>
                            </dt>
                            <dd>积分商城</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-credit-card"></span>
                            </dt>
                            <dd>优惠券</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-import"></span>
                            </dt>
                            <dd>收货地址</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-phone-alt"></span>
                            </dt>
                            <dd>客服/反馈</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-asterisk"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>
            {% if is_login %}
                <p>
                    <a href="{% url 'axf:logout' %}">退出</a>
                </p>
            {% endif %}
        </div>
    </div>

{% endblock %}



